Resources:
  RecordTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    Properties:
      TableName: ${self:service}-${self:provider.stage}-record-table
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: tableId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: baseId
          AttributeType: S
        - AttributeName: tenantId
          AttributeType: S
      KeySchema:
        - AttributeName: "tableId"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: baseIdGlobalIndex
          KeySchema:
            - AttributeName: baseId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: userIdGlobalIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: tenantIdGlobalIndex
          KeySchema:
            - AttributeName: tenantId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

